### ISSUE TITLE
加载某个视频的评论区导致应用崩溃闪退

### ISSUE THREAD

**Issue by GD-Slime** [ywmoyue/biliuwp-lite#395]
### Bug 描述

加载此视频: https://www.bilibili.com/video/BV1Lu4y187hZ 并点击其评论区，会直接导致应用卡死并闪退。

### 操作步骤

```plain text
1. 打开应用
2. 进入描述的视频
3. 点击评论区
4. 卡死
```

### 期望结果

正常加载评论区

### 日志

```
2023-11-07 14:14:08.4912|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/v2/reply?oid=918116163&plat=2&pn=1&ps=30&sort=1&type=1 |
2023-11-07 14:14:08.5699|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/v2/reply/main?oid=918116163&ps=30&mode=3&type=1&csrf=1741e860d1b10d9b6cc3f931b4133000&pagination_str={"offset":null} |
2023-11-07 14:14:08.6364|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/playurl?avid=918116163&cid=1322180294&qn=116&type=&otype=json&mid=7477307&fourk=1&fnver=0&fnval=4048 |
2023-11-07 14:14:08.7629|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/web-interface/nav? |
2023-11-07 14:14:08.9037|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/emote/user/panel/web?appkey=1d8b6e7d45233436&build=6235200&mobi_app=android&platform=android&ts=1699337649&business=reply&sign=3feb427ef1978c387bcd4ebf97662241 |
2023-11-07 14:14:08.9366|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/wbi/v2?aid=918116163&bvid=&cid=1322180294&wts=1699366449&w_rid=3b895fd993b66522d3b128f07ae54444 |
2023-11-07 14:14:09.0220|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/online/total?cid=1322180294&aid=918116163&bvid= |
2023-11-07 14:14:09.3931|ERROR|3|StringExtensions.ToRichTextBlock|富文本转换失败|无法找到与此错误代码关联的文本。

illegal xml character [Line: 4 Position: 74]    at Windows.UI.Xaml.Markup.XamlReader.Load(String xaml)
   at BiliLite.Extensions.StringExtensions.ToRichTextBlock(String txt, JObject emote)
2023-11-07 14:14:11.1119|ERROR|3|App.App_UnhandledException|程序运行出现错误|灾难性故障

灾难性故障
```

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by GD-Slime** [comment]
"像个知道自己犯错的小孩坦然面对该有的惩罚\u0014[笑哭]"
这个评论中的\u0014好像导致了此错误.
