### ISSUE TITLE
用户页搜索视频报错

### ISSUE THREAD

**Issue by ichigomikako** [ywmoyue/biliuwp-lite#426]
### Bug 描述

在用户页搜索视频出错

### 操作步骤

```plain text
1.进入用户页
2.搜索视频
3.搜索结果空白并报错
```

### 期望结果

能正常搜索视频

### 日志

```
2023-12-10 11:05:44.0829|INFO|2|StackTrace.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/space/archive/cursor?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=6235200&mobi_app=iphone&platform=android&ts=1702177544&vmid=3433092&ps=30&order=pubdate&aid=&sign={hasValue}|
2023-12-10 11:05:44.1038|INFO|2|StackTrace.LogRequest|网络请求: [GET]https://api.bilibili.com/x/space/wbi/acc/info?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=6235200&mid=3433092&mobi_app=iphone&platform=android&ts=1702177544&wts=1702206344&w_rid=26df78fa3af7a9659d30d6c25c948799 |
2023-12-10 11:05:44.2900|INFO|2|StackTrace.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/space?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=6235200&mobi_app=iphone&platform=android&ts=1702177544&vmid=3433092&sign={hasValue}|
2023-12-10 11:05:53.3903|ERROR|2|StackTrace.GetSubmitVideo|请求失败,没有数据返回|请求失败,没有数据返回    at BiliLite.Services.GrpcService.<SearchSpaceArchive>d__0.MoveNext() + 0x15f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at BiliLite.ViewModels.User.UserSubmitVideoViewModel.<GetSubmitVideo>d__60.MoveNext() + 0x1ad

2023-12-10 11:05:53.4108|ERROR|2|StackTrace.GetSubmitVideo|获取用户投稿失败|请求失败,没有数据返回    at BiliLite.Services.GrpcService.<SearchSpaceArchive>d__0.MoveNext() + 0x15f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at BiliLite.ViewModels.User.UserSubmitVideoViewModel.<GetSubmitVideo>d__60.MoveNext() + 0x1ad
```

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 代码贡献

我更擅长发现问题

**Comment by ichigomikako** [comment]
我看了一下，是我搜索时候打错字了，内容确实就该是空的，但是有报错 。
另外切换应用回到播放页后有个报错不知道是这么出现的，
不知道要怎么复现
```
2023-12-10 11:43:17.5198|ERROR|2|StackTrace.Send|POST请求失败https://api.bilibili.com/x/v2/history/report?|Call failed. An error occurred while sending the request: POST https://api.bilibili.com/x/v2/history/report    at Flurl.Http.FlurlRequest.<HandleExceptionAsync>d__35.MoveNext() + 0x21f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext() + 0x551
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext() + 0x8e4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at BiliLite.Models.Requests.BiliRequest.<Send>d__13.MoveNext() + 0x1b7

2023-12-10 11:43:17.5198|ERROR|2|StackTrace.ReportHistory|Object reference not set to an instance of an object.|Object reference not set to an instance of an object.    at BiliLite.Models.Requests.BiliRequest.<ConstructExResults>d__9.MoveNext() + 0x82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at BiliLite.Models.Requests.BiliRequest.<Send>d__13.MoveNext() + 0x3c7
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at BiliLite.Extensions.StringHttpExtensions.<PostHttpResultsAsync>d__8.MoveNext() + 0xe6
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at BiliLite.Extensions.ApiModelExtensions.<Request>d__1.MoveNext() + 0x39b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at BiliLite.Modules.PlayerVM.<ReportHistory>d__12.MoveNext() + 0x126
```

**Comment by GD-Slime** [comment]
我在尝试复现`在用户页搜索视频出错`的bug.
这个流程是否是：打开某一up的个人主页 -> 在搜索栏输入一个根本不存在于其发布视频的关键词 -> 空白并报错?
如果是这样的话, 那么会返回
```
2023-12-11 10:47:01.9008|ERROR|3|UserSubmitVideoViewModel.GetSubmitVideo|获取用户投稿失败|请求失败,没有数据返回    at BiliLite.Services.GrpcService.SearchSpaceArchive(String mid, Int32 page, Int32 pageSize, String keyword)
   at BiliLite.ViewModels.User.UserSubmitVideoViewModel.GetSubmitVideo()
```
属于正常现象(毕竟关键词没有匹配到), 后期优化可能会改掉这个报错。

**Comment by ichigomikako** [comment]
> I'm trying to reproduce the bug of `error in searching for videos on the user page'. Is this process as follows: Open a certain up's personal homepage -> Enter a keyword in the search bar that does not exist in the video posted by it -> Blank and Report an error? If so, it will return
>
> ```
> 2023-12-11 10:47:01.9008|ERROR|3|UserSubmitVideoViewModel.GetSubmitVideo|Failed to obtain user contributions|Request failed, no data returned at BiliLite.Services.GrpcService.SearchSpaceArchive(String mid, Int32 page, Int32 pageSize, String keyword)
> at BiliLite.ViewModels.User.UserSubmitVideoViewModel.GetSubmitVideo()
> ```
>
> This is a normal phenomenon (after all, the keyword is not matched), and this error may be corrected in later optimization.

right> 我在尝试复现`在用户页搜索视频出错`的bug. 这个流程是否是：打开某一up的个人主页 -> 在搜索栏输入一个根本不存在于其发布视频的关键词 -> 空白并报错? 如果是这样的话, 那么会返回
> 
> ```
> 2023-12-11 10:47:01.9008|ERROR|3|UserSubmitVideoViewModel.GetSubmitVideo|获取用户投稿失败|请求失败,没有数据返回    at BiliLite.Services.GrpcService.SearchSpaceArchive(String mid, Int32 page, Int32 pageSize, String keyword)
>    at BiliLite.ViewModels.User.UserSubmitVideoViewModel.GetSubmitVideo()
> ```
> 
> 属于正常现象(毕竟关键词没有匹配到), 后期优化可能会改掉这个报错。

对  就是这个流程

**Comment by forchannot** [comment]
直接在进入后首页右上角搜索时候也会报错
```
2023-12-19 20:36:54.1928|ERROR|2|StackTrace.CheckUpdateCookies|刷新Cookie失败|Object reference not set to an instance of an object.    at BiliLite.Modules.Account.<RefreshCookies>d__22.MoveNext() + 0x16d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at BiliLite.Modules.Account.<CheckUpdateCookies>d__19.MoveNext() + 0x14c

2023-12-19 20:37:16.1276|ERROR|2|StackTrace.App_UnhandledException|程序运行出现错误|Value cannot be null.
Parameter name: list    at BiliLite.Pages.HomePage.<SearchBox_TextChanged>d__25.MoveNext() + 0x12f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33

2023-12-19 20:37:16.4646|ERROR|2|StackTrace.App_UnhandledException|程序运行出现错误|Value cannot be null.
Parameter name: list    at BiliLite.Pages.HomePage.<SearchBox_TextChanged>d__25.MoveNext() + 0x12f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33

2023-12-19 20:37:17.0306|INFO|2|StackTrace.LogRequest|网络请求: [GET]https://s.search.bilibili.com/main/suggest?term=艾丝&main_ver=v1 |
2023-12-19 20:37:18.0301|INFO|2|StackTrace.LogRequest|网络请求: [GET]https://s.search.bilibili.com/main/suggest?term=艾&main_ver=v1 |
```

**Comment by GD-Slime** [comment]
@forchannot  能说一下复现的流程吗? 我这里尝试复现的流程：`打开应用 -> 搜索某个关键词 -> 一个字符一个字符退格 -> 搜索框为空` 这个流程没有报错。

**Comment by forchannot** [comment]
> @forchannot 能说一下复现的流程吗? 我这里尝试复现的流程：`打开应用 -> 搜索某个关键词 -> 一个字符一个字符退格 -> 搜索框为空` 这个流程没有报错。

录了段视频，压缩了下，不过应该能看清

https://github.com/ywmoyue/biliuwp-lite/assets/100580891/4637cb6a-37b8-4fa2-9e22-91577fd5e01a

**Comment by GD-Slime** [comment]
@forchannot 能否尝试重新登录一下呢？直接弹刷新cookie失败可能和这个问题也有关系。

**Comment by forchannot** [comment]
进行了重新登录，没有弹刷新cookie失败了，但是程序错误这个报错仍然存在

**Comment by forchannot** [comment]
> @forchannot 能说一下复现的流程吗? 我这里尝试复现的流程：`打开应用 -> 搜索某个关键词 -> 一个字符一个字符退格 -> 搜索框为空` 这个流程没有报错。

我这里测试并没有修复，4.6.25.0，报错仍然是
```log
2024-01-01 19:14:50.3150|ERROR|2|StackTrace.App_UnhandledException|程序运行出现错误|Value cannot be null.
Parameter name: list    at BiliLite.Pages.HomePage.<SearchBox_TextChanged>d__25.MoveNext() + 0x12f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33
```


https://github.com/ywmoyue/biliuwp-lite/assets/100580891/b9d2f5be-4b12-4692-93fc-f3897148d1fc

**Comment by ywmoyue** [comment]
看录屏这不是用户页搜索视频而是首页搜索视频，这是另一个问题了，需要重新提issue
