### ISSUE TITLE
某视频打开评论区后会导致整个软件卡死

### ISSUE THREAD

**Issue by GD-Slime** [ywmoyue/biliuwp-lite#440]
### Bug 描述

https://www.bilibili.com/video/BV1EN4y1h76r/
打开此视频后播放无问题，但是打开评论区就会卡死
目前原因未知，但是可能和上次一样是因为评论区特殊字符导致的

### 操作步骤

```plain text
略
```

### 期望结果

正常打开评论区

### 应用来源

Github/其他Github镜像站

### 代码贡献

是，我愿意提交代码

**Comment by GD-Slime** [comment]
```
2023-12-18 16:38:30.2924|ERROR|3|StringExtensions.ToRichTextBlock|富文本转换失败|无法找到与此错误代码关联的文本。

wfc: no '<' in attribute value [Line: 4 Position: 224]    at Windows.UI.Xaml.Markup.XamlReader.Load(String xaml)
   at BiliLite.Extensions.StringExtensions.ToRichTextBlock(String txt, JObject emote, Boolean isLive, String color, String fontWeight)
```
果然还是富文本转换失败 但是还是没找到哪个评论有问题

**Comment by GD-Slime** [comment]
`还有一首得老师的《叫魂》，我觉得前五没问题` 此评论引发了错误。但是看起来这句话并没有什么问题？
