### ISSUE TITLE
连按right健两次次后 视频会自己持续回退直到到0:00

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#771]
### Bug 描述

.

### 操作步骤

```plain text
.
```

### 期望结果

.

### 日志

2024-08-18 22:34:48.9244|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadCreateList https://api.bilibili.com/x/v3/fav/folder/created/list|
2024-08-18 22:34:48.9244|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/v3/fav/folder/created/list?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1723991689&up_mid=1465080156&pn=2&ps=20&sign={hasValue}|
2024-08-18 22:38:02.9158|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: Space|
2024-08-18 22:38:02.9158|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PlayPauseFunction|
2024-08-18 22:38:03.0280|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: Space|
2024-08-18 22:38:06.0824|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: Left|
2024-08-18 22:38:06.0829|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-08-18 22:38:06.1778|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: Left|
2024-08-18 22:38:06.2515|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: Left|
2024-08-18 22:38:06.2515|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-08-18 22:38:06.3020|TRACE|3|ShortcutKeyService.HandleKeyDown|keyPressAction: BiliLite.Models.Functions.PositionBackPressShortcutFunction|
2024-08-18 22:38:06.3975|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: Left|
2024-08-18 22:38:08.3572|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: Space|
2024-08-18 22:38:08.3572|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PlayPauseFunction|
2024-08-18 22:38:08.4498|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: Space|
2024-08-18 22:38:09.9375|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|参数错误。

Failed to start tracking the pointer, because it is already being tracked.
   at Windows.UI.Input.GestureRecognizer.ProcessDownEvent(PointerPoint value)
   at BiliLite.Controls.PlayerControl.Grid_PointerPressed(Object sender, PointerRoutedEventArgs e)

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
4.7.1.201+ 已处理

**Comment by Tpfdd** [comment]
> 4.7.1.201+ 已处理

赶紧发布吧，我受不了了，动不动就后退😭

**Comment by ywmoyue** [comment]
> > 4.7.1.201+ 已处理
> 
> 赶紧发布吧，我受不了了，动不动就后退😭

https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.1.202

**Comment by Tpfdd** [comment]
> > > 4.7.1.201+ 已处理
> > 
> > 
> > 赶紧发布吧，我受不了了，动不动就后退😭
> 
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.1.202

感谢

**Comment by TPAXcc** [comment]
> > > 4.7.1.201+ 已处理
> > 
> > 
> > 赶紧发布吧，我受不了了，动不动就后退😭
> 
> https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.1.202

测试已修复
