### ISSUE TITLE
快捷键设置页实际无法录制 up & down 键 和 mouse4&5 鼠标侧键

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#772]
### Bug 描述

另外建议 
up 改为 ↑ 
down 改为 ↓
目前描述可能使部分用户刚感到困惑

### 操作步骤

```plain text
。
```

### 期望结果

。

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
目前是直接用VirtualKey.ToString()得到的按键名称，以及没做鼠标键位的支持

然后我这边up&down录制是没问题的，可能需要分析日志

**Comment by TPAXcc** [comment]
> 目前是直接用VirtualKey.ToString()得到的按键名称，以及没做鼠标键位的支持
> 
> 然后我这边up&down录制是没问题的，可能需要分析日志

2024-08-19 11:49:02.4448|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetPlayInfo https://api.bilibili.com/x/player/wbi/v2|
2024-08-19 11:49:02.4448|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/wbi/v2?aid=1456311839&bvid=&cid=1631265809&wts=1724039342&w_rid=b5ffb9666aaea1f82e2fe58fdd2e78d9 |
2024-08-19 11:49:02.4448|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-08-19 11:49:02.4448|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-08-19 11:49:02.6444|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetOnline https://api.bilibili.com/x/player/online/total|
2024-08-19 11:49:02.6444|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/online/total?cid=1631265809&aid=1456311839&bvid= |
2024-08-19 13:20:01.5578|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: Down|
2024-08-19 13:20:01.5578|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|Object reference not set to an instance of an object.
   at BiliLite.Controls.Settings.ShortcutKeySettingsControl.ShortcutKeyService_OnRecordKeyDown(Object sender, InputKey e)
2024-08-19 13:20:01.5761|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|Object reference not set to an instance of an object.
   at BiliLite.Controls.Settings.ShortcutKeySettingsControl.ShortcutKeyService_OnRecordKeyDown(Object sender, InputKey e)
   at BiliLite.Services.ShortcutKeyService.HandleKeyDown(VirtualKey virtualKey)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2024-08-19 13:20:01.5806|ERROR|3|App.App_UnhandledException|程序运行出现错误|Object reference not set to an instance of an object.

2024-08-19 13:20:01.7019|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: Down|

**Comment by TPAXcc** [comment]
> > 目前是直接用VirtualKey.ToString()得到的按键名称，以及没做鼠标键位的支持
> > 然后我这边up&down录制是没问题的，可能需要分析日志
> 
> 2024-08-19 11:49:02.4448|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetPlayInfo [https://api.bilibili.com/x/player/wbi/v2|](https://api.bilibili.com/x/player/wbi/v2%7C) 2024-08-19 11:49:02.4448|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/wbi/v2?aid=1456311839&bvid=&cid=1631265809&wts=1724039342&w_rid=b5ffb9666aaea1f82e2fe58fdd2e78d9 | 2024-08-19 11:49:02.4448|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E) at Windows.System.Display.DisplayRequest.RequestRelease() at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value) 2024-08-19 11:49:02.4448|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E) at Windows.System.Display.DisplayRequest.RequestRelease() at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value) 2024-08-19 11:49:02.6444|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetOnline [https://api.bilibili.com/x/player/online/total|](https://api.bilibili.com/x/player/online/total%7C) 2024-08-19 11:49:02.6444|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/online/total?cid=1631265809&aid=1456311839&bvid= | 2024-08-19 13:20:01.5578|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: Down| 2024-08-19 13:20:01.5578|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|Object reference not set to an instance of an object. at BiliLite.Controls.Settings.ShortcutKeySettingsControl.ShortcutKeyService_OnRecordKeyDown(Object sender, InputKey e) 2024-08-19 13:20:01.5761|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|Object reference not set to an instance of an object. at BiliLite.Controls.Settings.ShortcutKeySettingsControl.ShortcutKeyService_OnRecordKeyDown(Object sender, InputKey e) at BiliLite.Services.ShortcutKeyService.HandleKeyDown(VirtualKey virtualKey) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 2024-08-19 13:20:01.5806|ERROR|3|App.App_UnhandledException|程序运行出现错误|Object reference not set to an instance of an object.
> 
> 2024-08-19 13:20:01.7019|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: Down|

这段对吗？

**Comment by ywmoyue** [comment]
是的，我看下

**Comment by ywmoyue** [comment]
@TPAXcc 试试https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.1.203 能不能录制up&down

**Comment by TPAXcc** [comment]
> @TPAXcc 试试https://github.com/ywmoyue/biliuwp-lite/releases/tag/v4.7.1.203 能不能录制up&down

测试 Up&Down 🆗了

鼠标侧键支持我新开个issues
