### ISSUE TITLE
捉到个崩溃

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#778]
### Bug 描述

整个应用崩溃

### 操作步骤

```plain text
1.打开应用
2.随便播放个视频
```

### 期望结果

.

### 日志

2024-08-20 19:42:17.4213|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/web-interface/view?&bvid=BV1Si421h7Lh |
2024-08-20 19:42:17.5158|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadFavorite https://api.bilibili.com/medialist/gateway/base/created|
2024-08-20 19:42:17.5158|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/medialist/gateway/base/created?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1724154138&rid=1456311839&up_mid=1465080156&type=2&pn=1&ps=100&sign={hasValue}|
2024-08-20 19:42:17.7693|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadVideoTags https://api.bilibili.com/x/tag/archive/tags|
2024-08-20 19:42:17.7695|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/tag/archive/tags?&aid=1456311839 |
2024-08-20 19:42:17.9046|INFO|3|QrCoderQrCodeService.GenerateQrCode|[QrCoder]生成二维码：https://b23.tv/BV1Si421h7Lh|
2024-08-20 19:42:18.0696|TRACE|3|PlayerControl.SetPlayItem|SetPlayItem,上报进度|
2024-08-20 19:42:18.0696|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ ReportHistory https://api.bilibili.com/x/v2/history/report|
2024-08-20 19:42:18.0696|INFO|3|BiliRequest.LogRequest|网络请求: [POST]https://api.bilibili.com/x/v2/history/report? access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1724154138&aid=1456311839&cid=1631265809&epid=&sid=0&progress=0&realtime=0&sub_type=1&type=3&sign={hasValue}|
2024-08-20 19:42:18.0935|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetComment https://api.bilibili.com/x/v2/reply|
2024-08-20 19:42:18.0935|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/v2/reply?oid=1456311839&plat=2&pn=1&ps=30&sort=1&type=1 |
2024-08-20 19:42:18.2079|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetComment https://api.bilibili.com/x/v2/reply/main|
2024-08-20 19:42:18.2079|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/v2/reply/main?oid=1456311839&ps=30&mode=3&type=1&csrf={hasValue}&pagination_str={"offset":null} |
2024-08-20 19:42:18.2560|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetPlayUrlUseWebApi https://api.bilibili.com/x/player/playurl|
2024-08-20 19:42:18.2560|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/playurl?avid=1456311839&cid=1631265809&qn=120&type=&otype=json&mid=1465080156&fourk=1&fnver=0&fnval=4048 |
2024-08-20 19:42:18.4908|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetEmote https://api.bilibili.com/x/emote/user/panel/web|
2024-08-20 19:42:18.4908|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/emote/user/panel/web?appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1724154138&business=reply&sign={hasValue}|
2024-08-20 19:42:18.9403|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetPlayInfo https://api.bilibili.com/x/player/wbi/v2|
2024-08-20 19:42:18.9403|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/wbi/v2?aid=1456311839&bvid=&cid=1631265809&wts=1724154139&w_rid=8e0e718b6036c962b82211f7e5433725 |
2024-08-20 19:42:18.9712|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by TPAXcc** [comment]
也许跟https://github.com/ywmoyue/biliuwp-lite/issues/768和https://github.com/ywmoyue/biliuwp-lite/issues/776是相同的bug?

**Comment by ywmoyue** [comment]
闪退了吗

**Comment by TPAXcc** [comment]
> 闪退了吗

是的 先蓝屏然后退
