### ISSUE TITLE
偶现播放报错

### ISSUE THREAD

**Issue by TPAXcc** [ywmoyue/biliuwp-lite#803]
### Bug 描述

未知BUG

### 操作步骤

```plain text
正常播放视频
```

### 期望结果

.

### 日志

2024-09-09 23:19:50.4116|TRACE|3|ShortcutKeyService.HandleKeyUp|keyReleaseAction: BiliLite.Models.Functions.StartHighRateSpeedPlayShortcutFunction|
2024-09-09 23:19:51.4164|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-09-09 23:19:51.4568|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-09-09 23:19:51.4568|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-09-09 23:19:51.4568|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-09-09 23:19:51.4568|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-09-09 23:19:51.4568|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-09-09 23:19:51.4568|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-09-09 23:19:52.3238|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-09-09 23:19:52.3528|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|灾难性故障

灾难性故障

   at FFmpegInteropX.FFmpegMediaSource.CreateMediaPlaybackItem()
   at BiliLite.Controls.Player.PlayDashUseFFmpegInterop(BiliDashPlayUrlInfo dashPlayUrlInfo, String userAgent, String referer, Double positon, Boolean needConfig, Boolean isLocal)
2024-09-09 23:19:52.3528|ERROR|3|PlayerControl.Player_ChangeEngine|播放失败:灾难性故障

灾难性故障
|
2024-09-09 23:19:52.3713|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|灾难性故障

灾难性故障

   at FFmpegInteropX.FFmpegMediaSource.CreateMediaPlaybackItem()
   at BiliLite.Controls.Player.PlayDashUseFFmpegInterop(BiliDashPlayUrlInfo dashPlayUrlInfo, String userAgent, String referer, Double positon, Boolean needConfig, Boolean isLocal)
2024-09-09 23:19:52.3713|ERROR|3|PlayerControl.Player_ChangeEngine|播放失败:灾难性故障

灾难性故障
|
2024-09-09 23:19:52.4067|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|灾难性故障

灾难性故障

   at FFmpegInteropX.FFmpegMediaSource.CreateMediaPlaybackItem()
   at BiliLite.Controls.Player.PlayDashUseFFmpegInterop(BiliDashPlayUrlInfo dashPlayUrlInfo, String userAgent, String referer, Double positon, Boolean needConfig, Boolean isLocal)
2024-09-09 23:19:52.4067|ERROR|3|PlayerControl.Player_ChangeEngine|播放失败:灾难性故障

灾难性故障
|
2024-09-09 23:19:54.2205|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|Unable to cast object of type 'System.Int32' to type 'System.Double'.
   at BiliLite.Controls.Player.get_BufferCache()
2024-09-09 23:19:54.2205|TRACE|29|App.CurrentDomain_FirstChanceException|错误发生|Unable to cast object of type 'System.Int32' to type 'System.Double'.
   at BiliLite.Controls.Player.get_BufferCache()
   at BiliLite.Controls.Player.set_BufferCache(Double value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2024-09-09 23:19:54.2205|TRACE|29|App.CurrentDomain_FirstChanceException|错误发生|Unable to cast object of type 'System.Int32' to type 'System.Double'.
   at BiliLite.Controls.Player.get_BufferCache()
   at BiliLite.Controls.Player.set_BufferCache(Double value)
--- End of stack trace from previous location where exception was thrown ---
   at BiliLite.Controls.Player.OnPlayerBufferingProgressChanged(MediaPlaybackSession session)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2024-09-09 23:19:54.2205|ERROR|29|App.App_UnhandledException|程序运行出现错误|Specified cast is not valid.

2024-09-09 23:19:54.2340|TRACE|29|App.CurrentDomain_FirstChanceException|错误发生|应用程序调用一个已为另一线程整理的接口。 (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))
   at Windows.UI.Xaml.Controls.UserControl..ctor()
   at BiliLite.Controls.MessageToast..ctor()
2024-09-09 23:19:54.6447|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: Space|
2024-09-09 23:19:54.6447|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PlayPauseFunction|
2024-09-09 23:19:54.8126|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: Space|
2024-09-09 23:19:55.9988|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: Escape|
2024-09-09 23:19:55.9988|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.CancelFullscreenFunction|
2024-09-09 23:19:56.2449|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: Escape|

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
看日志像是FFmpegInteropX库的问题
