### ISSUE TITLE
FFmpegInterop播放器个人目前发现的两个bug

### ISSUE THREAD

**Issue by CirnoSalt** [ywmoyue/biliuwp-lite#842]
### Bug 描述

1：进度条无法正常拖动、键盘左右键跳转失效，播放进度会直接弹回原位，但点击进度条可以跳转。
2：播放时会无故自动跳转到结尾，然后播放停止，同时主程序随机卡死（已附上日志）

### 操作步骤

```plain text
1：进度条无法正常拖动、键盘左右键跳转失效，播放进度会直接弹回原位，但点击进度条可以跳转。
2：播放时会无故自动跳转到结尾，然后播放停止，同时主程序随机卡死（已附上日志）
```

### 期望结果

可正常使用，不会出现如上bug

### 日志

```
2024-10-01 22:14:57.6428|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/region/index?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792098&sign={hasValue}|
2024-10-01 22:14:59.0267|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://passport.bilibili.com/api/oauth2/info?appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792099&access_token={hasValue}&sign={hasValue}|
2024-10-01 22:14:59.0869|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/feed/index?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792099&flush=0&idx=0&login_event=2&network=wifi&open_event=&pull=true&qn=32&style=2&sign={hasValue}|
2024-10-01 22:14:59.2298|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/account/mine?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792099&sign={hasValue}|
2024-10-01 22:14:59.3791|INFO|3|BiliRequest.LogRequest|网络请求: [GET]http://app.biliapi.net/x/v2/space?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792099&vmid=431491835&sign={hasValue}|
2024-10-01 22:14:59.6183|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/feed/index?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792100&flush=0&idx=1727792097&login_event=2&network=wifi&open_event=&pull=false&qn=32&style=2&sign={hasValue}|
2024-10-01 22:15:00.0922|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/feed/index?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792100&flush=0&idx=1727792086&login_event=2&network=wifi&open_event=&pull=false&qn=32&style=2&sign={hasValue}|
2024-10-01 22:15:27.6824|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadHistoryCore https://api.bilibili.com/x/web-interface/history/cursor|
2024-10-01 22:15:27.6966|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/web-interface/history/cursor?max=0&view_at=0&business= |
2024-10-01 22:15:29.4066|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadVideoDetail https://app.bilibili.com/x/v2/view|
2024-10-01 22:15:29.4066|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/view?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792129&bvid=BV1BfxCekEB8&plat=0&sign={hasValue}|
2024-10-01 22:15:29.7627|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadVideoDetail https://api.bilibili.com/x/web-interface/view|
2024-10-01 22:15:29.7627|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/web-interface/view?&bvid=BV1BfxCekEB8 |
2024-10-01 22:15:29.8926|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadFavorite https://api.bilibili.com/medialist/gateway/base/created|
2024-10-01 22:15:29.8928|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/medialist/gateway/base/created?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792130&rid=113220069101680&up_mid=431491835&type=2&pn=1&ps=100&sign={hasValue}|
2024-10-01 22:15:30.0446|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadVideoTags https://api.bilibili.com/x/tag/archive/tags|
2024-10-01 22:15:30.0446|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/tag/archive/tags?&aid=113220069101680 |
2024-10-01 22:15:30.1413|INFO|3|QrCoderQrCodeService.GenerateQrCode|[QrCoder]生成二维码：https://b23.tv/BV1BfxCekEB8|
2024-10-01 22:15:30.2864|TRACE|3|PlayerControl.SetPlayItem|SetPlayItem,上报进度|
2024-10-01 22:15:30.2864|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ ReportHistory https://api.bilibili.com/x/v2/history/report|
2024-10-01 22:15:30.2864|INFO|3|BiliRequest.LogRequest|网络请求: [POST]https://api.bilibili.com/x/v2/history/report? access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792130&aid=113220069101680&cid=26059539397&epid=&sid=0&progress=0&realtime=0&sub_type=1&type=3&sign={hasValue}|
2024-10-01 22:15:30.3062|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetComment https://api.bilibili.com/x/v2/reply|
2024-10-01 22:15:30.3062|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/v2/reply?oid=113220069101680&plat=2&pn=1&ps=30&sort=1&type=1 |
2024-10-01 22:15:30.3849|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetComment https://api.bilibili.com/x/v2/reply/main|
2024-10-01 22:15:30.3849|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/v2/reply/main?oid=113220069101680&ps=30&mode=3&type=1&csrf={hasValue}&pagination_str={"offset":null} |
2024-10-01 22:15:30.7010|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetEmote https://api.bilibili.com/x/emote/user/panel/web|
2024-10-01 22:15:30.7010|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/emote/user/panel/web?appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792131&business=reply&sign={hasValue}|
2024-10-01 22:15:30.7517|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetPlayUrlUseWebApi https://api.bilibili.com/x/player/playurl|
2024-10-01 22:15:30.7517|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/playurl?avid=113220069101680&cid=26059539397&qn=127&type=&otype=json&mid=431491835&fourk=1&fnver=0&fnval=4048 |
2024-10-01 22:15:30.9013|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetPlayInfo https://api.bilibili.com/x/player/wbi/v2|
2024-10-01 22:15:30.9013|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/wbi/v2?aid=113220069101680&bvid=&cid=26059539397&wts=1727792131&w_rid=3f03642e96bdb8db3b3f21e1a045dd3b |
2024-10-01 22:15:30.9985|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetOnline https://api.bilibili.com/x/player/online/total|
2024-10-01 22:15:30.9985|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/online/total?cid=26059539397&aid=113220069101680&bvid= |
2024-10-01 22:15:31.4677|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-10-01 22:16:41.8986|DEBUG|3|PlayerControl.Player_PlayMediaEnded|视频结束，上报进度|
2024-10-01 22:16:41.8986|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ ReportHistory https://api.bilibili.com/x/v2/history/report|
2024-10-01 22:16:41.8986|INFO|3|BiliRequest.LogRequest|网络请求: [POST]https://api.bilibili.com/x/v2/history/report? access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727792202&aid=113220069101680&cid=26059539397&epid=&sid=0&progress=3173&realtime=3173&sub_type=1&type=3&sign={hasValue}|
```

### 应用来源

Github/其他Github镜像站

### 安装方式

脚本安装

### 系统版本

Windows 11 21H2 (Build 22000)

### 设备类型

笔记本

### 设备架构

x64

### 应用架构

x64

### 代码贡献

我更擅长发现问题

**Comment by ywmoyue** [comment]
第一个问题有相关日志吗，当前版本只要有键盘操作就会有Trace日志记录，例如
```
2024-10-01 18:24:56.3658|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: Control|
2024-10-01 18:24:56.4841|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: Control|
```

**Comment by CirnoSalt** [comment]
> 第一个问题有相关日志吗，当前版本只要有键盘操作就会有Trace日志记录，例如
> 
> ```
> 2024-10-01 18:24:56.3658|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: Control|
> 2024-10-01 18:24:56.4841|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: Control|
> ```
  

```
2024-10-02 01:28:46.6092|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ SetRegions https://app.bilibili.com/x/v2/region/index|
2024-10-02 01:28:46.6564|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/region/index?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803727&sign={hasValue}|
2024-10-02 01:28:48.2458|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ CheckLoginState https://passport.bilibili.com/api/oauth2/info|
2024-10-02 01:28:48.2458|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://passport.bilibili.com/api/oauth2/info?appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803728&access_token={hasValue}&sign={hasValue}|
2024-10-02 01:28:48.3041|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetRecommend https://app.bilibili.com/x/v2/feed/index|
2024-10-02 01:28:48.3041|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/feed/index?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803728&flush=0&idx=0&login_event=2&network=wifi&open_event=&pull=true&qn=32&style=2&sign={hasValue}|
2024-10-02 01:28:48.4634|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetHomeUserCard https://app.bilibili.com/x/v2/account/mine|
2024-10-02 01:28:48.4634|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/account/mine?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803728&sign={hasValue}|
2024-10-02 01:28:48.6055|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetHomeUserCard http://app.biliapi.net/x/v2/space|
2024-10-02 01:28:48.6055|INFO|3|BiliRequest.LogRequest|网络请求: [GET]http://app.biliapi.net/x/v2/space?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803729&vmid=431491835&sign={hasValue}|
2024-10-02 01:28:48.7409|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetRecommend https://app.bilibili.com/x/v2/feed/index|
2024-10-02 01:28:48.7409|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/feed/index?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803729&flush=0&idx=1727803729&login_event=2&network=wifi&open_event=&pull=false&qn=32&style=2&sign={hasValue}|
2024-10-02 01:29:11.7579|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadData https://api.bilibili.com/x/v2/history/toview|
2024-10-02 01:29:11.7579|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/v2/history/toview?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803752&ps=100&sign={hasValue}|
2024-10-02 01:29:19.4052|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadHistoryCore https://api.bilibili.com/x/web-interface/history/cursor|
2024-10-02 01:29:19.4273|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/web-interface/history/cursor?max=0&view_at=0&business= |
2024-10-02 01:29:20.9459|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadVideoDetail https://app.bilibili.com/x/v2/view|
2024-10-02 01:29:20.9459|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://app.bilibili.com/x/v2/view?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803761&bvid=BV1BfxCekEB8&plat=0&sign={hasValue}|
2024-10-02 01:29:21.4132|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadVideoDetail https://api.bilibili.com/x/web-interface/view|
2024-10-02 01:29:21.4132|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/web-interface/view?&bvid=BV1BfxCekEB8 |
2024-10-02 01:29:21.5890|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadFavorite https://api.bilibili.com/medialist/gateway/base/created|
2024-10-02 01:29:21.5890|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/medialist/gateway/base/created?access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803762&rid=113220069101680&up_mid=431491835&type=2&pn=1&ps=100&sign={hasValue}|
2024-10-02 01:29:21.8322|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ LoadVideoTags https://api.bilibili.com/x/tag/archive/tags|
2024-10-02 01:29:21.8322|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/tag/archive/tags?&aid=113220069101680 |
2024-10-02 01:29:21.9509|INFO|3|QrCoderQrCodeService.GenerateQrCode|[QrCoder]生成二维码：https://b23.tv/BV1BfxCekEB8|
2024-10-02 01:29:22.2340|TRACE|3|PlayerControl.SetPlayItem|SetPlayItem,上报进度|
2024-10-02 01:29:22.2399|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ ReportHistory https://api.bilibili.com/x/v2/history/report|
2024-10-02 01:29:22.2399|INFO|3|BiliRequest.LogRequest|网络请求: [POST]https://api.bilibili.com/x/v2/history/report? access_key={hasValue}&appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803762&aid=113220069101680&cid=26059539397&epid=&sid=0&progress=0&realtime=0&sub_type=1&type=3&sign={hasValue}|
2024-10-02 01:29:22.2722|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetComment https://api.bilibili.com/x/v2/reply|
2024-10-02 01:29:22.2722|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/v2/reply?oid=113220069101680&plat=2&pn=1&ps=30&sort=1&type=1 |
2024-10-02 01:29:22.3877|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetComment https://api.bilibili.com/x/v2/reply/main|
2024-10-02 01:29:22.3877|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/v2/reply/main?oid=113220069101680&ps=30&mode=3&type=1&csrf={hasValue}&pagination_str={"offset":null} |
2024-10-02 01:29:22.6806|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetPlayUrlUseWebApi https://api.bilibili.com/x/player/playurl|
2024-10-02 01:29:22.6806|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/playurl?avid=113220069101680&cid=26059539397&qn=127&type=&otype=json&mid=431491835&fourk=1&fnver=0&fnval=4048 |
2024-10-02 01:29:22.8754|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetEmote https://api.bilibili.com/x/emote/user/panel/web|
2024-10-02 01:29:22.8763|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/emote/user/panel/web?appkey=27eb53fc9058f8c3&build=75900200&mobi_app=iphone&platform=android&ts=1727803763&business=reply&sign={hasValue}|
2024-10-02 01:29:22.9895|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetPlayInfo https://api.bilibili.com/x/player/wbi/v2|
2024-10-02 01:29:22.9895|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/wbi/v2?aid=113220069101680&bvid=&cid=26059539397&wts=1727803763&w_rid=3734d91ac4e75f32f29ca9650d689da6 |
2024-10-02 01:29:23.0997|TRACE|3|ApiModelExtensions.Request|ÇëÇó¼ÇÂ¼ GetOnline https://api.bilibili.com/x/player/online/total|
2024-10-02 01:29:23.0997|INFO|3|BiliRequest.LogRequest|网络请求: [GET]https://api.bilibili.com/x/player/online/total?cid=26059539397&aid=113220069101680&bvid= |
2024-10-02 01:29:23.6328|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|在意外的时间调用了方法。 (Exception from HRESULT: 0x8000000E)
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at BiliLite.Controls.PlayerControl.KeepScreenOn(Boolean value)
2024-10-02 01:29:27.2782|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: →|
2024-10-02 01:29:27.4002|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: →|
2024-10-02 01:29:27.4002|TRACE|3|ShortcutKeyService.HandleKeyUp|keyUpAction: BiliLite.Models.Functions.PositionForwardShortcutFunction|
2024-10-02 01:29:31.4748|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:31.4748|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:31.5782|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:32.1418|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:32.1418|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:32.3614|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:32.3614|TRACE|3|ShortcutKeyService.HandleKeyUp|keyReleaseAction: BiliLite.Models.Functions.PositionBackPressShortcutFunction|
2024-10-02 01:29:32.9324|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:32.9324|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:33.0634|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:33.8085|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:33.8085|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:33.9170|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:34.5413|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:34.5413|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:34.6153|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:35.3359|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:35.3359|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:35.4954|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:36.0259|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:36.0259|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:36.1539|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:36.4671|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:36.4671|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:36.5567|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:36.7694|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:36.7694|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:36.7694|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:36.8195|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:36.8195|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:36.9543|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:41.3808|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:41.3808|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:41.5139|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:41.6405|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:41.6405|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:41.7832|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:41.9734|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:41.9734|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:42.0459|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:42.1982|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:42.1982|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:42.2867|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:43.0884|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:43.0884|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:43.1821|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:43.3005|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:43.3005|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:43.4252|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:43.5845|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:43.5845|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:43.6930|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:44.5624|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:44.5624|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:44.6656|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:44.9360|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:44.9360|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:45.0695|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:45.9605|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:45.9605|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:46.0243|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:46.1274|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:46.1274|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:46.3497|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:29:46.3497|TRACE|3|ShortcutKeyService.HandleKeyUp|keyReleaseAction: BiliLite.Models.Functions.PositionBackPressShortcutFunction|
2024-10-02 01:29:46.3497|TRACE|3|ShortcutKeyService.HandleKeyDown|key down: ←|
2024-10-02 01:29:46.3497|TRACE|3|ShortcutKeyService.HandleKeyDown|keyDownAction: BiliLite.Models.Functions.PositionBackFunction|
2024-10-02 01:29:46.3729|TRACE|3|ShortcutKeyService.HandleKeyUp|key up: ←|
2024-10-02 01:30:37.1849|TRACE|3|MainPage.Current_Suspending|应用挂起|
```

刚才发现这个现象只在部分视频内出现，并且不是100%复现，比如https://b23.tv/BV1BfxCekEB8
同时还又找到了一个bug，播放器设置为FFmpegInterop后，关闭重启客户端又会自己变回Native。

**Comment by ywmoyue** [comment]
关闭重启客户端又会自己变回Native是设置控件这里初始化写错了，设置完之后不打开设置页就一直是正常的

**Comment by ywmoyue** [comment]
试试4.7.4.501，刷了一些视频目前没发现`播放时会无故自动跳转到结尾`这个问题有再出现

**Comment by CirnoSalt** [comment]
> 试试4.7.4.501，刷了一些视频目前没发现`播放时会无故自动跳转到结尾`这个问题有再出现

自动跳转结尾确认修复了，不过进度条拖动和左右快捷键这版还是一样的问题。

**Comment by TPAXcc** [comment]
似乎与 #803 是类似问题

**Comment by ywmoyue** [comment]
> 似乎与 #803 是类似问题

不是同一个问题，#803日志中的数据类型转换问题在这次提交中处理了 https://github.com/ywmoyue/biliuwp-lite/commit/c3d75ce98d6f64f0e706120e83a4b64f408f9201

可以再观察一段时间看看#803还有没有出现
