### ISSUE TITLE
新版本配色不统一

### ISSUE THREAD

**Issue by Shaddoll126** [ywmoyue/biliuwp-lite#899]
### Bug 描述

视频底部进度显示为红色，但其余主题色均为蓝色，希望能统一颜色并提供主题色设置

### 操作步骤

```plain text
无需操作
```

### 期望结果

主题色统一

### 截图

![image](https://github.com/user-attachments/assets/87ca472d-bea4-4170-9bcd-5a13a3746456)
![image](https://github.com/user-attachments/assets/628033b9-7227-47f9-a25a-64e465a23d20)
![image](https://github.com/user-attachments/assets/58343a99-75d6-49f9-aee7-6c457a3ee7bb)

### 应用来源

Github/其他Github镜像站

### 代码贡献

我更擅长发现问题

**Comment by JimHans** [comment]
底部的进度条确实没跟着主题色走，但软件全局的主题色是默认跟随Windows系统主题色的，需要调整主题色的话你可以在Windows的设置->个性化->颜色那里调整看看

**Comment by ywmoyue** [comment]
关于颜色自定义的功能我在想是像 https://github.com/ZzzzzzzSkyward/biliuwp-lite-fix 一样提供xaml文件让用户自行修改还是说提供几个固定的设置项让用户修改

![image](https://github.com/user-attachments/assets/4bf4c307-aac1-48bf-84f8-3e33c847abb5)

**Comment by ProJend** [comment]
我想他的重点是主题色统一，颜色自定义不是bug

**Comment by ProJend** [comment]
#1048

**Comment by ProJend** [comment]
@ywmoyue 能判断是nuget包的问题还是应用本身的问题吗，该问题只在release生成下出现，另外新建的空白应用没有这个问题。有没有解决思路？
### xaml源代码
```
<Page
    xmlns:controls1="using:CommunityToolkit.WinUI.Controls"
    ...>
    <controls1:ColorPicker/>
</Page>
```
### 错误日志
```
2025-02-13 14:52:26.4347|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|0
Parameter name: System.Nullable`1<Double>
   at Microsoft.Toolkit.Uwp.UI.Controls.Microsoft_Toolkit_Uwp_UI_Controls_XamlTypeInfo.XamlUserType.CreateFromString(String input)
2025-02-13 14:52:26.6044|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|无法找到与此错误代码关联的文本。

Failed to assign to property 'Windows.UI.Xaml.ResourceDictionary.Source' because the type 'Windows.Foundation.String' cannot be assigned to the type 'Windows.Foundation.Uri'. [Line: 0 Position: 0]
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at BiliLite.BiliLite_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_17_BlankPage1()
2025-02-13 14:52:26.6044|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|无法找到与此错误代码关联的文本。

Failed to assign to property 'Windows.UI.Xaml.ResourceDictionary.Source' because the type 'Windows.Foundation.String' cannot be assigned to the type 'Windows.Foundation.Uri'. [Line: 0 Position: 0]
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at BiliLite.BiliLite_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_17_BlankPage1()
   at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType)
   at BiliLite.App.Navigation(Object arguments, Boolean prelaunch)
2025-02-13 14:52:26.6345|TRACE|3|App.CurrentDomain_FirstChanceException|错误发生|无法找到与此错误代码关联的文本。

Failed to assign to property 'Windows.UI.Xaml.ResourceDictionary.Source' because the type 'Windows.Foundation.String' cannot be assigned to the type 'Windows.Foundation.Uri'. [Line: 0 Position: 0]
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at BiliLite.BiliLite_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_17_BlankPage1()
   at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType)
   at BiliLite.App.Navigation(Object arguments, Boolean prelaunch)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-02-13 14:52:26.6563|ERROR|3|App.App_UnhandledException|程序运行出现错误|XAML parsing failed.
```

**Comment by ywmoyue** [comment]
![Image](https://github.com/user-attachments/assets/7c82610e-2723-45b8-8f23-53ee55205857)

@ProJend 我试了下没有出现问题

**Comment by ProJend** [comment]
@ywmoyue 你试错了，是这个控件出了问题
[CommunityToolkit.WinUI.Controls.ColorPicker](https://www.nuget.org/packages/CommunityToolkit.WinUI.Controls.ColorPicker/)

**Comment by ywmoyue** [comment]
> [@ywmoyue](https://github.com/ywmoyue) 你试错了，是这个控件出了问题 [CommunityToolkit.WinUI.Controls.ColorPicker](https://www.nuget.org/packages/CommunityToolkit.WinUI.Controls.ColorPicker/)

好的，确实是有这个错误

**Comment by ywmoyue** [comment]
如果新建的空白应用没有这个问题的话，那可能是有依赖库的冲突然后release编译后有些关键代码被剪了，晚点有空我也看一下

**Comment by ProJend** [comment]
@ywmoyue 感谢大佬抽出时间来检查，这是有该问题的分支
[Color](https://github.com/ProJend/biliuwp-lite/tree/color)

**Comment by ProJend** [comment]
@ywmoyue 感谢大佬抽出时间来检查，这是有该问题的分支
[Color](https://github.com/ProJend/biliuwp-lite/tree/color)

**Comment by ywmoyue** [comment]
@ProJend 我在新的空白应用中复现了，应该是和`Microsoft.Toolkit.Uwp.UI.Controls`这个包冲突了
